DATA_PATH = joinpath(TetrisAI.PROJECT_ROOT, "data")
MODELS_PATH = joinpath(TetrisAI.PROJECT_ROOT, "saved_models")
STATES_PATH = joinpath(DATA_PATH, "states")
LABELS_PATH = joinpath(DATA_PATH, "labels")
SCOREBOARD_PATH = joinpath(DATA_PATH, "scoreboard")
